run:
  timeout: 3m
  tests: true

linters:
  # Do not use global disable-all here so the CLI can pass --disable flags
  # (we'll disable problematic analyses in the CI invocation).
  disable-all: false
  enable:
    - gosimple     # simplify code
    - gofmt        # formatting (check only)
    - ineffassign  # detect ineffectual assignments
    - unused       # detect unused code (replacement for deadcode)
    - errcheck     # check for unchecked errors
  # Keep the config conservative; staticcheck/govet will be run separately in CI

linters-settings:
  errcheck:
    # Allow ignoring common close error checks in tests and shutdown code.
    excludeFuncs:
      - Close

issues:
  # Allow a moderate number of issues per linter to avoid noisy CI failures while
  # still surfacing important problems. Adjust thresholds as the project matures.
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - gofmt
      text: "should have a comment"
  exclude-dirs:
    - web
    - static

# For reproducible runs in CI, lock the version in the workflow rather than here.
