site_name: WhoTalkie Documentation
site_description: Documentation for the WhoTalkie PTT streaming project
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Protocol:
    - Opus Transport: opus-protocol.md
  - Architecture: architecture.md
  - Ops: ops.md
theme:
  name: material
plugins:
  - search
