---
name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUN_LINT: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod download

      - name: Run go vet
        run: go vet ./...

      - name: Install golangci-lint (build with runner toolchain)
        if: env.RUN_LINT == 'true'
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.0
          echo "GOBIN: $(go env GOPATH)/bin"
          ls -la $(go env GOPATH)/bin || true

      - name: Run golangci-lint (optional)
        if: env.RUN_LINT == 'true'
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          golangci-lint --version
          golangci-lint run --timeout=6m

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test ./... -v -coverprofile=coverage/coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/coverage.out
