name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install MkDocs and theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Build site
        run: mkdocs build --site-dir site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
